### ISSUE TITLE
Unable to load shared library

### ISSUE THREAD

**Issue by bvarga** [matthiasg/zeromq-node-windows#1]
On Windows Server Enterprise (32bit) I got the followin error messge, running the examples:

```
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Unable to load shared library c:\Users\bvarga\test\zeromq-node-windows\c
ompiled\0.6\win32\ia32\zeromq.node
    at Object..node (module.js:472:11)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at bindings (c:\Users\bvarga\test\zeromq-node-windows\node_modules\bindings
\bindings.js:72:15)
    at Object.<anonymous> (c:\Users\bvarga\test\zeromq-node-windows\lib\index.j
s:9:29)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
```

with node 0.6.14
any ideas? thx.

**Comment by matthiasg** [comment]
Right now it is compiled for x64 I think can you try ?

---

From: bvarga
Sent: 06.04.2012 15:28
To: Matthias Gtzke
Subject: [zeromq-node-windows] Unable to load shared library (#1)

On Windows Server Enterprise (32bit) I got the followin error messge, running the examples:

```
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Unable to load shared library c:\Users\bvarga\test\zeromq-node-windows\c
ompiled\0.6\win32\ia32\zeromq.node
    at Object..node (module.js:472:11)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at bindings (c:\Users\bvarga\test\zeromq-node-windows\node_modules\bindings
\bindings.js:72:15)
    at Object.<anonymous> (c:\Users\bvarga\test\zeromq-node-windows\lib\index.j
s:9:29)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
```

with node 0.6.14
any ideas? thx.

---

Reply to this email directly or view it on GitHub:
https://github.com/matthiasg/zeromq-node-windows/issues/1

**Comment by matthiasg** [comment]
it is compiled with vs2008, it needs the c runtime AND libzmq.dll. Can you check with depends.exe whether they are next to your startup path or in your path ?

**Comment by bvarga** [comment]
Thank's, 
I forgot to copy libzmq.dll to my directory.Now It works fine under 32bit and 64bit.

**Comment by matthiasg** [comment]
great! it has been compiled for node 32bit btw.
